apiVersion: v1
kind: ConfigMap
metadata:
  name: finbank-nginx-config
  namespace: finbank-gateway
data:
  default.conf: |
    server {
      listen 80;

      location /api/auth/ {
        proxy_pass http://auth-service.finbank-new.svc.cluster.local:8081;
      }

      location / {
        proxy_pass http://monolith.finbank-legacy.svc.cluster.local:8080;
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: finbank-gateway
  namespace: finbank-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: finbank-gateway
  template:
    metadata:
      labels:
        app: finbank-gateway
    spec:
      containers:
      - name: nginx
        image: nginx:1.27-alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/nginx/conf.d
          name: nginx-config
      volumes:
      - name: nginx-config
        configMap:
          name: finbank-nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: finbank-gateway
  namespace: finbank-gateway
spec:
  type: LoadBalancer
  selector:
    app: finbank-gateway
  ports:
  - port: 80
    targetPort: 80
